### ISSUE TITLE
the button doesn't layout properly if the titleLabel has multiple lines

### ISSUE THREAD

**Issue by hariseldon78** [DavydLiu/DLRadioButton#58] opened 2016-10-13 02:54 UTC

**Comment by DavydLiu** [comment] 2016-10-13 16:13
Could you provide a screenshot please?

**Comment by hariseldon78** [comment] 2016-10-13 16:58
Sure, sorry for not doing that, i was really tired :)

Here is from the simulator:
![2016-10-13_18-52-21](https://cloud.githubusercontent.com/assets/133625/19358554/964e7268-9176-11e6-9716-b91147e5981a.png)

Here is the view debugging:
![2016-10-13_18-54-38](https://cloud.githubusercontent.com/assets/133625/19358602/c2f8f98c-9176-11e6-8045-c64162567e1a.png)
![2016-10-13_18-54-38](https://cloud.githubusercontent.com/assets/133625/19358560/9d8de7c0-9176-11e6-8523-824ded8a60cc.png)

I created the buttons programmatically and added some constraint  previous.bottom = next.top.
I'll try to prepare a simple project to reproduce the issue.

**Comment by hariseldon78** [comment] 2016-10-13 17:32
Here is the project. Xcode version is 8.0 (8A218a)
[RadioButtonIssue.zip](https://github.com/DavydLiu/DLRadioButton/files/527781/RadioButtonIssue.zip)

**Comment by hariseldon78** [comment] 2016-10-13 17:42
i'm looking into it and it seems that the problem happens for simple UIButton as well, so it's not something specific to this library. I'll let you know if i find a solution.

**Comment by hariseldon78** [comment] 2016-10-13 18:02
Ok, i found it. i make you a pull request to fix this problem

**Comment by korgx9** [comment] 2016-10-24 05:34
Have the same issue. When your PR will be merged?

**Comment by hariseldon78** [comment] 2016-10-24 11:52
the reaction seems slow, in the while you could use my fork: https://github.com/hariseldon78/DLRadioButton

**Comment by DavydLiu** [comment] 2016-12-28 18:21
I think this is by design, not that `UIButton` has a problem. 

Another way to do this is:
```
radiobutton.lineBreakMode = NSLineBreakByWordWrapping;
radiobutton.numberOfLines = 0;
```

**Closed** 2016-12-28 18:21 UTC
