### ISSUE TITLE
Failed to render instance of DLRadioButton

### ISSUE THREAD

**Issue by abingeorgev** [DavydLiu/DLRadioButton#21] opened 2016-01-21 07:31 UTC
I am getting this error everytime I run my project. Using storyboard. Xcode version 7.2.

" Failed to render instance of DLRadioButton: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance." And as said, the UI gets stuck for some time.

**Comment by DavydLiu** [comment] 2016-01-21 17:36
I'm currently using Xcode 7.2 and using storyboard to add `DLRadioButton`, there is no such warnings. However, did you update to `1.4.5`, it fixes performance issues that might cause this warning, if you have a large number of `DLRadioButton`s in your storyboard.

**Comment by abingeorgev** [comment] 2016-01-22 09:27
Yes am using the latest version.

**Comment by DavydLiu** [comment] 2016-02-01 00:50
I updated project to `1.4.6`, although never have been able to reproduce the issue you described. Is that possible because you have a huge storyboard which affects rendering of `DLRadioButton`?

**Comment by DavydLiu** [comment] 2016-02-23 21:23
Closing the issue now, please feel free to re-open it if the issue still exists.

**Closed by DavydLiu** 2016-02-23 21:23 UTC
